language: python
python: 3.6

cache: pip

install:
  - pip install -r requirements.txt

script:
  # create the missing files
  - cp config.json.default config.json

  # create the zip
  - tar --exclude=".git" -zcvf /tmp/omega-logserver.tar.gz .

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - /tmp/omega-logserver.tar.gz
  on:
    branch: master